name: Release to Maven Repository

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            # Extract version from release tag (remove 'v' prefix if present)
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          else
            # Use manual input version
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Update version in build.gradle.kts
        run: |
          sed -i 's/project\.version = "[^"]*"/project.version = "${{ steps.version.outputs.VERSION }}"/' ./launcher/build.gradle.kts
          sed -i 's/val isRelease = false/val isRelease = true/' ./launcher/build.gradle.kts

      - name: Publish to Maven Repository
        env:
          ORG_GRADLE_PROJECT_releasesUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_releasesPassword: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publishMavenAllPlatformsPublicationToReleasesRepository --no-daemon --configuration-cache --parallel
