name: Release
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, linux, linux-aarch64, mac, mac-aarch64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Clean build folder
        run: ./gradlew clean

      - name: Build for ${{ matrix.platform }}
        run: ./gradlew shadowJar -Pplatform=${{ matrix.platform }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: meld-launcher-${{ matrix.platform }}
          path: launcher/build/libs
          if-no-files-found: warn
          retention-days: 90
          compression-level: 6
          overwrite: true

#  publish:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      - name: Download build artifacts
#        uses: actions/download-artifact@v4
#        with:
#          pattern: meld-launcher-*
#          path: build/libs/
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Publish to Releases
#        run: ./gradlew publishMavenPublicationToReleasesRepository
#        env:
#          MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
#          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
